### ISSUE TITLE
Fix ERD

### ISSUE THREAD

**Issue by syarifs** [altacapstone36/go-server#3]
sesuaikan ERD dengan [UI/UX](https://www.figma.com/file/sk4STvibDhUDds3fqw0fO9/Design-File).

**Comment by clowny9** [comment]
minta tolong ditambahin fitur untuk med list, butuh nama dokter dan resep obat yang diberikan seperti gambar di bawah ini 
![image](https://user-images.githubusercontent.com/95902218/172040827-50c8ef75-b5f8-48eb-b949-c1dc3cf81f43.png)
